### ISSUE TITLE
workbox not working in dev

### ISSUE THREAD

**Issue by MillionQW** [davidgaroro/vuetify-todo-pwa#1]
Vuetify-todo-pwa is a great project for me to learn PWA with Vue! Thx your project.

But when I run your project in dev, I found that workbox not working?
I tried to build the project and run the project in dist, workbox is work.

At the beginning, I thought that the reason is ```registerServiceWorker.js``` has a ```if (process.env.NODE_ENV === 'production')```. I tried to remove it. But workbox still not working in dev.

**Comment by davidgaroro** [comment]
Hi @MillionQW !

I'm very glad to know that my project is being useful to you! 😄 

As I read in the [official vuecli-plugin-pwa documentation](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa#vuecli-plugin-pwa)

> **The service worker added with this plugin is only enabled in the production environment** (e.g. only if you run npm run build or yarn build). **Enabling service worker in a development mode is not a recommended practice**, because it can lead to the situation when previously cached assets are used and the latest local changes are not included.
> 
> Instead, in the development mode the noopServiceWorker.js is included. This service worker file is effectively a 'no-op' that will reset any previous service worker registered for the same host:port combination.
> 
> If you need to test a service worker locally, build the application and run a simple HTTP-server from your build directory. It's recommended to use a browser incognito window to avoid complications with your browser cache.

Regards!
