### ISSUE TITLE
Place of webpack configuration

### ISSUE THREAD

**Issue by ivansteff** [davidgaroro/vuetify-todo-pwa#2]
where can I find `webpack.config` ?
Or where should I write a couple of lines in the Webpack configuration?

**Comment by briansanger** [comment]
The documentation on the Vue cli page might be helpful @ivansteff. Vue is now integrating Webpack into the framework, abstracting away the `webpack.config`.
https://cli.vuejs.org/guide/webpack.html

I found the learning curve slightly steeper than I originally anticipated. The section explaining how to use `vue inspect` to output the webpack.config to a file you can review was beneficial.
https://cli.vuejs.org/guide/webpack.html#inspecting-the-project-s-webpack-config
